# Generated by Django 5.1.3 on 2024-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_startdate_goal_deposit_goal_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalvalue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
