# Generated by Django 5.1.3 on 2024-12-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_deposit_alter_goal_goalvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalvalue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='withdrawal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
