# Generated by Django 5.1.3 on 2024-12-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindexpenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('duedate', models.DateField()),
                ('paid', models.BooleanField(default=True)),
                ('latepayment', models.BooleanField(default=False)),
                ('fine', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('finalvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('totalexpenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kindexpenses.kindexpense')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
