# Generated by Django 5.1.3 on 2024-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='finalvalue',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='latepayment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='totalexpenses',
        ),
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
