# Generated by Django 5.1.3 on 2024-12-13 12:26

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_finalvalue_remove_expense_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='duedate',
            field=models.CharField(help_text='Insira dia e mês DD-MM', max_length=5, validators=[expenses.models.validate_day_month]),
        ),
    ]
