# Generated by Django 5.1.3 on 2024-12-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='goal',
            new_name='name',
        ),
    ]
