# Generated by Django 5.1.3 on 2024-12-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inflows', '0001_initial'),
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='revenues.revenue'),
        ),
    ]
